# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20171204_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('picId', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='configparam',
            name='action',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
