# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20171205_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picId',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
